# AUTOGENERATED! DO NOT EDIT! File to edit: Chapter_2.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'intf', 'bird', 'classify_image']

# %% Chapter_2.ipynb 1
from fastai.vision.all import *
import gradio as gr

def bird(x): return x[0].isupper()

# %% Chapter_2.ipynb 3
learn = load_learner('bird_model.pkl')

# %% Chapter_2.ipynb 5
categories = ["Northern Cardinal", "Blue Jay", "American Crow", "Black-capped Chickadee",
    "White-breasted Nuthatch", "Mourning Dove", "House Sparrow", "House Finch",
    "Downy Woodpecker", "Red-bellied Woodpecker", "Tufted Titmouse", "Carolina Wren",
    "Eastern Screech-Owl", "Great Horned Owl", "American Robin", "Barn Swallow",
    "Tree Swallow", "Baltimore Oriole", "Eastern Bluebird", "Ruby-throated Hummingbird",
    "Red-winged Blackbird", "Common Yellowthroat", "Indigo Bunting", "Eastern Meadowlark",
    "Canada Goose", "Snow Goose", "Sandhill Crane", "Yellow Warbler", "Warbling Vireo",
    "Swainson's Thrush", "Northern Parula", "Black-throated Green Warbler", "Hermit Thrush",
    "Rose-breasted Grosbeak", "Dark-eyed Junco", "American Tree Sparrow", "Snow Bunting",
    "Rough-legged Hawk", "Common Redpoll", "Pine Siskin", "Mallard", "Wood Duck",
    "Great Blue Heron", "Killdeer", "Belted Kingfisher", "Spotted Sandpiper",
    "Double-crested Cormorant", "Bald Eagle", "Red-tailed Hawk", "Cooper's Hawk",
    "Sharp-shinned Hawk", "Peregrine Falcon", "American Kestrel", "Osprey",
    "Northern Flicker", "Pileated Woodpecker", "Cedar Waxwing", "Yellow-bellied Sapsucker",
    "Scarlet Tanager", "Northern Mockingbird", "Brown Thrasher", "Orchard Oriole",
    "Eastern Phoebe", "Great Crested Flycatcher"]

def classify_image(img):
    pred, idx, probs = learn.predict(img)
    class_idx = learn.dls.vocab.o2i[pred]
    return dict(zip(sorted(categories), map(float, probs)))

# %% Chapter_2.ipynb 7
intf = gr.Interface(
    fn=classify_image, 
    inputs=gr.Image(type='pil'), 
    outputs=gr.Label(), 
    examples=[
        'Common Yellowthroat 1.jpg', 'Common Yellowthroat 2.jpg', 'Mourning Dove.jpg', 'Killdeer.jpg', 'Sharp-shinned Hawk.jpg', 
        'Ruby-throated Hummingbird 1.jpg', 'Ruby-throated Hummingbird 2.jpg'
    ])
intf.launch(inline=False)
